@BoundVerse_HostAddress = http://localhost:5037

GET {{BoundVerse_HostAddress}}/book/b7be5978-7d29-4ad6-afeb-8d25eb9871be
Accept: application/json

###

POST {{BoundVerse_HostAddress}}/book
Accept: application/json
Content-Type: application/json

{
    "title": "Lord of the Rings",
    "description": "Tolkiens Trillogy",
    "numberOfPages": 999,
    "year": 1930,
    "category": {
        "name": "Novels"
    }
}

###

POST {{BoundVerse_HostAddress}}/category
Accept: application/json
Content-Type: application/json

{
    "name": "Novels"
}

###

patch {{BoundVerse_HostAddress}}/book/cf1700af-ea08-4fac-a16c-f4a37033bef4
Accept: application/json
Content-Type: application/json

{
    "title": "Lord of the Things",
    "description": "Tolkiens Trillogy",
    "numberOfPages": 999,
    "year": 1930,
    "category": {
        "name": "Novels"
    }
}
